---
title: "Severity Scores: BGD MSNA 2019"
author: "REACH BGD"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE, warning = FALSE, message=FALSE}


#

knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning = FALSE,
                      out.width = "100%")

rm(list=ls())
user<-"zack"
population<-c("Host","Refugee")[1]
data_process<-c("checking", "cleaning", "analysis")[3]
analysis_phase<-c("basic","relationship_testing")[1]

library(dplyr)
# library(GISutils)
# detach("package:butteR", unload = TRUE)
library(nngeo)
library(dplyr)
library(hypegrammaR)
library(koboquest)
library(stringr)
library(lubridate)
library(rgdal)
library(sf)
library(anytime)
library(srvyr)
library(forcats)

source("Functions/colours.R")
source("Functions/ActivatePaths.R")
source("Functions/make_composite_indicators_bgd_msna_2019.R")
source("Functions/calculate_shelter_topology.R")
source("Functions/general_utils.R")
source("Functions/recode_to_severity_bgd_msna2019.R")
source("Functions/recoding_severity/recode_SNFI_severity_bgd2019.R")
source("Functions/recoding_severity/recode_HEALTH_severity_bgd2019.R")
source("Functions/recoding_severity/recode_COPING_severity_bgd2019.R")
source("Functions/recoding_severity/recode_EDUCATION_severity_bgd2019.R")
source("Functions/recoding_severity/recode_WASH_severity_bgd2019.R")
# source( "Functions/recoding_severity/recode_PROTECTION_severity_bgd2019.R")
#LOAD DATA
#############
HH_kobo_questions<-read.csv(survey_path,stringsAsFactors = FALSE)
HH_kobo_choices<-read.csv(choices_path, stringsAsFactors = FALSE)
wash_combo_table<-read.csv(wash_severity_combination_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA, "NA"))
wash_errors<- read.csv(wash_error_path,na.strings = c("", " "))



incidents_per_camp<-read.csv("Inputs/DAPs/Severity Analysis_Protection_Reported Incidents per camp_REACH.csv", stringsAsFactors = FALSE, na.strings=c("", " ", NA, "NA"))


# host<-read.csv(HH_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA)
# host_indiv<-read.csv(Indiv_path, strcingsAsFactors = FALSE, na.strings=c("", " ", NA))
# ref<-read.csv(HH_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA))
# ref_indiv<-read.csv(Indiv_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA))


HH<-read.csv(HH_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA, "NA"))
Indiv<-read.csv(Indiv_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA, "NA"))
HH_kobo_questionnaire<-koboquest::load_questionnaire(HH,questions = HH_kobo_questions,choices = HH_kobo_choices, choices.label.column.to.use = "label..english")
pop<- read.csv(pop_path, stringsAsFactors = FALSE, na.strings=c("", " ", NA))
################
#FILTER TO ONLY YES CONSENT AND MAKE COMPOSTIES
################
HH_yes_consent<- HH %>% filter(informed_consent=="yes")
indiv_yes_consent<-Indiv %>% filter(X_submission__uuid %in% HH_yes_consent$X_uuid)
# debugonce(make_composite_indicators_bgd_msna_2019)


enough_water_cols_to_fix<-HH_yes_consent %>% select(starts_with("enough_water")) %>% colnames()
rows_to_fix<-which(HH_yes_consent$X_uuid %in% wash_errors$uuid)
HH_yes_consent[rows_to_fix,enough_water_cols_to_fix] <-sapply(HH_yes_consent[rows_to_fix,enough_water_cols_to_fix],function(x)x<-NA) 


composite_indicators<-make_composite_indicators_bgd_msna_2019(hh_data = HH_yes_consent,  individual_data = indiv_yes_consent,population = population)

HH_with_composite<-HH_yes_consent %>% left_join(composite_indicators$household_composites,by="X_uuid")

HH_with_composite<-butteR::remove_concat_select_multiple(HH_with_composite,questionnaire = HH_kobo_questionnaire)

# debugonce(recode_HEALTH_severity_bgd2019)

HH_severity<-HH_with_composite

HH_severity<- recode_WASH_severity_bgd2019(HH_severity, individual_data = indiv_yes_consent, population=population, wash_combo_table = wash_combo_table)

HH_severity<-recode_SNFI_severity_bgd2019(hh_data= HH_severity, individual_data=indiv_yes_consent, population=population)

HH_severity<-recode_HEALTH_severity_bgd2019(hh_data= HH_severity, individual_data=indiv_yes_consent, population=population)
HH_severity<-recode_EDUCATION_severity_bgd2019(hh_data= HH_severity, individual_data=indiv_yes_consent, population=population)
HH_severity<-recode_PROTECTION_severity_bgd2019(hh_data= HH_severity, individual_data=indiv_yes_consent, population=population)

HH_severity<-butteR::questionnaire_factorize_categorical(HH_severity,questionnaire = HH_kobo_questionnaire,return_full_data = TRUE )

# HH_severity %>% select(ends_with(".structure"),starts_With("improvement.none))
# HH_severity<-recode_COPING_severity_bgd2019(hh_data= HH_with_composite, individual_data=indiv_yes_consent, population=population)


###############
# CALCULATE WEIGHTS
if(population=="Refugee"){
HH_severity<-HH_severity %>%
  group_by(!!sym(strata)) %>%
  filter(n()>10) %>%
  ungroup()

pop<-pop %>% 
    filter(!is.na(Camp)& is.na(Block)) %>% 
    mutate(
      camp_id=str_replace(Camp, "Total","") %>% trimws(),
      Total.Families=as.numeric(Total.Families)
    ) %>% 
    select(camp_id, Total.Families,Total.Individuals)

}else{
  pop[[sf_strata]]<-if_else(pop[[sf_strata]] =="Teknaf Sadar" , "Teknaf",pop[[sf_strata]]) 
} 

# pop%>% write.csv("pops.csv")
# CLEAN POPULATION DATA ---------------------------------------------------



weighting<-map_to_weighting(sampling.frame = pop, 
                            data.stratum.column = strata,
                            data = HH_severity, 
                            sampling.frame.population.column =sf_pop,
                            sampling.frame.stratum.column = sf_strata)



HH_svy_ob<-map_to_design(data=HH_severity, weighting_function = weighting)



```

# `r ifelse(population=="Host","Host Community", "Refugees")`

##SNFI

```{r,fig.height=10}
# asdf<- HH_srv$variables %>% select(starts_with("sev.snfi.structure")) %>% colnames()
# HH_srv$variables %>% select("X_uuid", starts_with("int.snfi.imp"),starts_with("sev.snfi.structure")) %>% data.frame() %>% 
  # mutate(asdf2=if_else(rowSums(.[asdf],na.rm = TRUE)==0,1,0)) %>% filter(asdf2==1)

HH_srv<-as_survey(HH_svy_ob)

severity_components<-HH_srv %>% select(intersect(starts_with("sev_score"), contains( ".sub."))) %>% colnames()
severity_totals_over_3<-HH_srv %>% select(intersect(starts_with("sev_score"), ends_with("total_over_3"))) %>% colnames()

severity_sub_component_nfi<- HH_srv %>% select(starts_with("sev_score.snfi.sub")) %>% colnames()
severity_int_component_health<-HH_srv %>% select(starts_with("int.health")) %>% colnames()
severity_int_component_education<-HH_srv %>% select(starts_with("int.education")) %>% colnames()
severity_sector_finals= HH_srv %>% select(intersect(starts_with("sev_score"),ends_with(".total"))) %>% colnames
HH_srv$variables[,severity_components]<-lapply(HH_srv$variables[,severity_components], as.factor)
HH_srv$variables[,severity_components]<-lapply(HH_srv$variables[,severity_components], function(x)forcats::fct_expand(x,"1","2", "3", "4","5") %>% fct_relevel("1","2", "3", "4","5"))

HH_srv$variables[,severity_sector_finals]<-lapply(HH_srv$variables[,severity_sector_finals], as.factor)
HH_srv$variables[,severity_sector_finals]<-lapply(HH_srv$variables[,severity_sector_finals], function(x)forcats::fct_expand(x,"1","2", "3", "4","5") %>% fct_relevel("1","2", "3", "4","5"))

# stratified_severities_over3<-butteR::barplot_grouped_binaries(design = HH_srv,list_of_variables = severity_totals_over_3,aggregation_level = strata )
# stratified_severities_over3

```

##HEALTH
```{r,fig.height=10}
severity_sub_component_graphs<-list()
for(i in 1:length(severity_sub_component_nfi)){
  severity_sub_component_graphs[[severity_sub_component_nfi[[i]]]]<-HH_srv %>%
    group_by(!!sym(strata),!!sym(severity_sub_component_nfi[[i]]), .drop=FALSE) %>%
    summarise(mean.stat=survey_mean(na.rm=TRUE, vartype="ci")) %>%
    ggplot(aes(x=as.factor(!!sym(strata)), y=mean.stat, fill=!!sym(severity_sub_component_nfi[[i]])))+
    geom_bar(position=position_dodge(), stat="identity", colour='black') +
    scale_fill_manual(values=severity_colors)+
    # colorspace::scale_fill_discrete_diverging (palette= " Green-Orange")+
    geom_errorbar(aes(ymin=mean.stat_low, ymax=mean.stat_upp), width=.2,position=position_dodge(.9))+
    scale_y_continuous(breaks=seq(0,1, by=0.1),labels = scales::percent_format(accuracy = 1))+
    labs(x=strata)+
    coord_flip()
}

for(i in 1:length(severity_components)){
  severity_sub_component_graphs[[severity_components[[i]]]]<-HH_srv %>%
    group_by(!!sym(strata),!!sym(severity_components[[i]]), .drop=FALSE) %>%
    summarise(mean.stat=survey_mean(na.rm=TRUE, vartype="ci")) %>%
    ggplot(aes(x=as.factor(!!sym(strata)), y=mean.stat, fill=!!sym(severity_components[[i]])))+
    geom_bar(position=position_dodge(), stat="identity", colour='black') +
    scale_fill_manual(values=severity_colors)+
    # colorspace::scale_fill_discrete_diverging (palette= " Green-Orange")+
    geom_errorbar(aes(ymin=mean.stat_low, ymax=mean.stat_upp), width=.2,position=position_dodge(.9))+
    scale_y_continuous(breaks=seq(0,1, by=0.1),labels = scales::percent_format(accuracy = 1))+
    labs(x=strata)+
    coord_flip()
}
severity_sub_component_graphs


stratified_intermediate_health_graphs<-butteR::barplot_grouped_binaries(design = HH_srv,list_of_variables = severity_int_component_health,aggregation_level = strata )

overall_intermediate_health_graphs<-butteR::barplot_grouped_binaries(design = HH_srv,list_of_variables = severity_int_component_health,aggregation_level = NULL)
overall_intermediate_education_graphs<-butteR::barplot_grouped_binaries(design = HH_srv,list_of_variables = severity_int_component_education,aggregation_level = NULL)




severity_sector_final_graphs<-list()
for(i in 1:length(severity_sector_finals)){
  severity_sector_final_graphs[[severity_sector_finals[[i]]]]<-HH_srv %>% 
    group_by(!!sym(strata),!!sym(severity_sector_finals[[i]]), .drop=FALSE) %>% 
    summarise(mean.stat=survey_mean(na.rm=TRUE, vartype="ci")) %>% 
    ggplot(aes(x=as.factor(!!sym(strata)), y=mean.stat, fill=!!sym(severity_sector_finals[[i]])))+
    scale_fill_manual(values=severity_colors,aesthetics="fill")+
    # colorspace::scale_fill_discrete_diverging (palette= " Green-Orange")+
    # scale_color_discrete_sequential(palette = "Blues", nmax = 6, order = 2:6)+
    geom_bar(position=position_dodge(), stat="identity", colour='black') +
    geom_errorbar(aes(ymin=mean.stat_low, ymax=mean.stat_upp), width=.2,position=position_dodge(.9))+
    scale_y_continuous(breaks=seq(0,1, by=0.1),labels = scales::percent_format(accuracy = 1))+
    labs(x=strata)+
    coord_flip()
}


severity_sector_final_graphs



```

```{r}
overall_intermediate_health_graphs



````

##EDUCATION
```{r,fig.height=20, out.width= "100%"}

stratified_intermediate_health_graphs

overall_intermediate_education_graphs
````

##WASH
###BY VULNERABILITIES
```{r}

```




##PROTECTION
###By Vulnerabilities

```{r}

```
##By vulnearbility criteria

```{r}
# severity_sub_component_graphs<-list()
# for(i in 1:length(severity_sub_component)){
# severity_sub_component_graphs[[severity_sub_component[[i]]]]<-HH_srv %>% 
#   group_by(I.HH_CHAR.gender_hoh.HH,!!sym(severity_sub_component[[i]]), .drop=FALSE) %>% 
#   summarise(mean.stat=survey_mean(na.rm=TRUE, vartype="ci")) %>% 
#   ggplot(aes(x=as.factor(I.HH_CHAR.gender_hoh.HH), y=mean.stat, fill=!!sym(severity_sub_component[[i]])))+
#     geom_bar(position=position_dodge(), stat="identity", colour='black') +
#   geom_errorbar(aes(ymin=mean.stat_low, ymax=mean.stat_upp), width=.2,position=position_dodge(.9))+
#   scale_y_continuous(breaks=seq(0,1, by=0.1),labels = scales::percent_format(accuracy = 1))+
#   coord_flip()
# }
# severity_sub_component_graphs


HH_CHAR_vulnerabilities<-c("I.HH_CHAR.size.HH", "I.HH_CHAR.gender_hoh.HH",
"I.HH_CHAR.education_level.HH", 
"I.HH_CHAR.dependency_ratio_classification.HH")
# HH_srv$variables %>% select(starts_with("I.HH_CHAR")) %>% colnames() %>% dput()

# HH_srv$variables$i.hh_char
# severity_against_vulnerability_graphs<-list()
# rezzys<-list()
# for(i in 1:length(HH_CHAR_vulnerabilities)){
#   vulnerability_characteristic<-HH_CHAR_vulnerabilities[[i]]
#   print(vulnerability_characteristic)
#   results_summarised<-HH_srv %>% 
#     group_by(!!sym(vulnerability_characteristic),sev_score.snfi.total, .drop=FALSE) %>% 
#     summarise(mean.stat=survey_mean(na.rm=TRUE, vartype="ci")) 
#   rezzys[[i]]<-results_summarised
#   severity_against_vulnerability_graphs[[vulnerability_characteristic]]<-results_summarised %>% 
#     ggplot(aes(x=as.factor(!!sym(vulnerability_characteristic)), y=mean.stat, fill=sev_score.snfi.total))+
#     geom_bar(position=position_dodge(), stat="identity", colour='black') +
#     colorspace::scale_fill_discrete_diverging (palette= " Green-Orange")+
#     
#     geom_errorbar(aes(ymin=mean.stat_low, ymax=mean.stat_upp), width=.2,position=position_dodge(.9))+
#     scale_y_continuous(breaks=seq(0,1, by=0.1),labels = scales::percent_format(accuracy = 1))+
#     coord_flip()
# }
# severity_against_vulnerability_graphs

```

```{r, eval=FALSE}

sev_score_cols<-c("sev_score.snfi.structure", "sev_score.snfi.tenure", "sev_score.snfi.power", 
"sev_score.snfi.nfi", "sev_score.snfi.number4", "sev_score.snfi.number3", 
"sev_score.snfi.number2", "sev_score.snfi.number1", 
"sev_score.snfi.total.s4", "sev_score.snfi.total.s3", "sev_score.snfi.total.s2", 
"sev_score.snfi.total")
sev_score_cols <- HH_svy_ob$variables %>% select(starts_with("sev_score"), -ends_with(".s5")) %>% colnames()

HH_svy_ob$variables[,sev_score_cols]<-lapply(HH_svy_ob$variables[,sev_score_cols], as.factor)
sev_score_cols<-c(sev_score_cols,"rank_priority_need_2")
strata_boundary<-sf::st_read(dsn = strata_boundary_gdb, strata_boundary_layer)
# debugonce(butteR::mean_proportion_table)
sev_scores_aggregated<-butteR::mean_proportion_table(design = HH_svy_ob,list_of_variables=sev_score_cols,aggregation_level = strata,round_to = 2,return_confidence = FALSE,na_replace = TRUE)

strata_boundary<- sf::st_read(strata_boundary_gdb,strata_boundary_layer)
severity_spatial<-strata_boundary %>% left_join(sev_scores_aggregated,, by=c("adm4_en"="union_name"))

library(tmap)
my_map<-tm_shape(severity_spatial) +
  tm_polygons("sev_score.snfi.total.4")
my_map<- my_map+ tm_shape(severity_spatial)+
  tm_polygons("sev_score.snfi.total.3")
tmap_mode("view")
my_map2<-tm_shape(severity_spatial) +
  tm_polygons(c("sev_score.snfi.total.4","sev_score.snfi.total.3","sev_score.snfi.total.2","sev_score.snfi.total.1"),
              title=c("SNFI Sev. 4", "SNFI Sev. 3","SNFI Sev. 2","SNFI Sev. 1"),popup.vars=c("Sev 4"="sev_score.snfi.total.4",
                                                                               "Sev 3"="sev_score.snfi.total.3","Sev 2"="sev_score.snfi.total.2",
                                                                               "Sev 1"="sev_score.snfi.total.1")) +
  tm_facets(sync = TRUE, ncol = 2)
if(population=="Host"){
  sev_score_cols<-"sev_score.snfi.total"
my_map2<-tm_shape(severity_spatial) +
  tm_polygons(c("sev_score.snfi.total.3","sev_score.snfi.total.2","sev_score.snfi.total.1"),
              title=c( "SNFI Sev. 3","SNFI Sev. 2","SNFI Sev. 1"),popup.vars=c(
                                                                               "Sev 3"="sev_score.snfi.total.3","Sev 2"="sev_score.snfi.total.2",
                                                                               "Sev 1"="sev_score.snfi.total.1")) +
  tm_facets(sync = TRUE, ncol = 2)
}

```

#INTERSECTORAL


```{r}
  getmode <- function(v) {
    uniqv <- unique(v)
    uniqv[which.max(tabulate(match(v, uniqv)))]
  }
norm_vec <- function(x) sqrt(sum(x^2))
lp_vec<-function(x)((sum(x^2)))^(1/(length(x)))
# lp_vec2<-function(x)(sum(x^2))^(1/5)
lp_vecb<-function(x)(sum(x^(1/length(x))))^length(x)

lp_vecc<-function(x)(sum(x^(length(x))))^(1/length(x))

# Hmisc::latexTranslate("((sum(x^(1/length(x))))^length(x))/(length(x)^length(x))")

lp_benini<-function(x) ((sum(x^(1/length(x))))^length(x))/(length(x)^length(x))

# lp_benini<-function(x)(sum(x^1/length(x)))#/(x^length(x))

HH_srv<-as_survey(HH_svy_ob)
HH_srv2<-HH_srv
sectoral_totals<-HH_srv %>% select(intersect(starts_with("sev_score"), ends_with(".total"))) %>% colnames()
HH_srv$variables[,sectoral_totals]<-sapply(HH_srv$variables[,sectoral_totals], as.numeric)
# sapply(HH_srv$variables[,sectoral_totals], range) %>% range()

HH_srv2$variables<-HH_srv$variables %>% 
  mutate(
    sev_score_intersectoral_max.total=apply(HH_srv$variables[,sectoral_totals],1,max),
    sev_score_intersectoral_mean.total= apply(HH_srv$variables[,sectoral_totals],1, mean),
    sev_score_intersectoral_mean_round.total=round(sev_score_intersectoral_mean.total,0),
    sev_score_intersectoral_mean_roundup.total=ceiling(sev_score_intersectoral_mean.total),
    sev_score_intersectoral_median.total=apply(HH_srv$variables[,sectoral_totals],1, median),
    sev_score_intersectoral_mode.total=apply(HH_srv$variables[,sectoral_totals],1, getmode),
    # sev_score_intersectoral_norm.total=apply(HH_srv$variables[,sectoral_totals],1, norm_vec),
    sev_score_intersectoral_l2norm.total=apply(HH_srv$variables[,sectoral_totals] %>% as.matrix,1, Rtreemix::L2.norm),
    sev_score_intersectoral_lp_benini.total=apply(HH_srv$variables[,sectoral_totals], 1,lp_benini),#/(length(sectoral_totals)^length(sectoral_totals)),
    # sev_score_intersectoral_lpnorm.total=apply(HH_srv$variables[,sectoral_totals] ,1, lp_vec),
    # sev_score_intersectoral_lpnorm2.total=apply(HH_srv$variables[,sectoral_totals] ,1, lp_vec2),
    # sev_score_intersectoral_lpvecb.total=apply(HH_srv$variables[,sectoral_totals] ,1, lp_vecb),
    sev_score_intersectoral_lpvecc.total=apply(HH_srv$variables[,sectoral_totals] ,1, lp_vecc),
    sev_score_intersectoral_lpvecc_rescaled.total=scales::rescale(HH_srv2$variables$sev_score_intersectoral_lpvecc.total, to = c(1, 6))
    
    
  )





 

inter_sectoral_totals<-HH_srv2 %>% select(intersect(starts_with("sev_score_intersectoral"), ends_with(".total"))) %>% colnames()


HH_srv2$variables[,inter_sectoral_totals]$sev_score_intersectoral_lp_benini.total %>% range()

butteR:::barplot_by_group(HH_srv2,list_of_variables = inter_sectoral_totals,aggregation_level = NULL ,binary=FALSE)+ggtitle("intersectoral severity scores")
# butteR::barplot_grouped_binaries(HH_srv2,list_of_variables = all_sectoral_totals,aggregation_level = NULL)

# butteR:::barplot_by_group(HH_srv2,list_of_variables = all_sectoral_totals,aggregation_level = strata ,binary=FALSE)


intersectoral_matrix_with_sectoral<- HH_srv2$variables[,c(sectoral_totals,"sev_score_intersectoral_mean.total")]
# pca_intersectoral_matrix_with_sectoral<-princomp(x = intersectoral_matrix_with_sectoral)
pca_intersectoral_matrix_with_sectoral<-prcomp(intersectoral_matrix_with_sectoral, scale=TRUE)
# fit <- prcomp(USArrests, scale=T)


# ggbiplot::


```

###INTERSECTORAL SEVERITIES ANALYZED

```{r}

all_severity_totals<-HH_srv %>% select(intersect(starts_with("sev_score"), ends_with(".total"))) %>%colnames()


# HH_srv2$variables[,all_severity_totals]<-sapply(HH_srv2$variables[,all_severity_totals],as.integer) 



all_severity_totals_by_camp<-butteR::mean_proportion_table(design = HH_srv2, list_of_variables =  all_severity_totals, aggregation_level = "camp_name",questionnaire = HH_kobo_questionnaire, return_confidence = FALSE)



```
